services:
  cache:
    image: redis:7.2
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --save 20 1
  db:
    image: postgres:16
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  cronjob:
    image: curlimages/curl:latest
    env_file: .env
    entrypoint: >
      /bin/sh -c "
        trap 'exit 0' TERM INT;
        while true; do
          curl -X POST host.docker.internal:$PORT/events/score_job -H 'api-key: $CRONJOB_API_KEY';
          sleep 10 & wait \$!;
        done
      "
